- name: Create demo directory
  file:
    path=/opt/demo
    state=directory

- name: Download and Unarchive package
  unarchive:
    src: "{{ artifact_url }}"
    dest: /opt/demo
    remote_src: yes

- name: Install demo systemd unit file
  template:
    src=demo.j2
    dest=/etc/systemd/system/demo.service

- name: Start demo
  systemd:
    state=restarted
    name=demo
    daemon_reload=yes
