version: '2'

services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - pg

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - pg

volumes:

  prometheus-data:
    driver: local

  grafana-data:
    driver: local

networks:
  
  pg:
    driver: bridge